_wandb:
    value:
        cli_version: 0.27.2
        e:
            vo2kv4u8hb8bhqxc8uwlrxsx06wzcqaj:
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "482685030400"
                        used: "420941197312"
                email: khalilakremi0@gmail.com
                executable: C:\Users\user\anaconda3\envs\traffic_marl\python.exe
                git:
                    commit: 53bac268155dba3efdede218788859d4a1ff56a1
                    remote: https://github.com/khalil-akremi/rl-traffic-signal-control.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-26fabaff-a8e8-7c92-f2b2-8661b0164cfb
                host: LAPTOP-JR3NLK8H
                memory:
                    total: "33549283328"
                os: Windows-10-10.0.26200-SP0
                program: -m training.Optimize
                python: CPython 3.10.20
                root: C:\Users\user\traffic_marl
                startedAt: "2026-06-12T11:27:35.547741Z"
                writerId: vo2kv4u8hb8bhqxc8uwlrxsx06wzcqaj
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 35
                - 77
            "2":
                - 1
                - 35
                - 77
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.20
            "5": 0.27.2
            "8":
                - 3
            "10":
                - 20
            "12": 0.27.2
            "13": windows-amd64
environment:
    value:
        delta_time: 5
        min_green: 5
        net_file: network/grid.net.xml
        num_seconds: 3600
        route_file: network/grid.rou.xml
        use_gui: false
        yellow_time: 2
mappo:
    value:
        batch_size: 64
        clip_epsilon: 0.07176080525033553
        entropy_coef: 0.0939570899695548
        gamma: 0.99
        lr_actor: 1.3645172964517399e-05
        lr_critic: 1.4134514115954247e-05
        update_epochs: 6
        value_coef: 0.5
model:
    value:
        embedding_dim: 128
        gat_heads: 4
        gat_hidden_dim: 128
        gat_layers: 2
training:
    value:
        episodes: 30
        seed: 42
        update_freq: 256
